module org.unisa.musicplaylistmanager {
    requires javafx.controls;
    requires javafx.fxml;
    requires java.base;
    requires java.desktop;


    exports org.unisa.musicplaylistmanager.app;
    opens org.unisa.musicplaylistmanager.app to javafx.fxml;
    exports org.unisa.musicplaylistmanager.core.observer;
    opens org.unisa.musicplaylistmanager.core.observer to javafx.fxml;
    exports org.unisa.musicplaylistmanager.core.iterator;
    opens org.unisa.musicplaylistmanager.core.iterator to javafx.fxml;
    exports org.unisa.musicplaylistmanager.core.navigation;
    opens org.unisa.musicplaylistmanager.core.navigation to javafx.fxml;
    exports org.unisa.musicplaylistmanager.player.model;
    opens org.unisa.musicplaylistmanager.player.model to javafx.fxml;
    exports org.unisa.musicplaylistmanager.player.controller;
    opens org.unisa.musicplaylistmanager.player.controller to javafx.fxml;
    exports org.unisa.musicplaylistmanager.player.service;
    opens org.unisa.musicplaylistmanager.player.service to javafx.fxml;
    exports org.unisa.musicplaylistmanager.player.state;
    opens org.unisa.musicplaylistmanager.player.state to javafx.fxml;
    exports org.unisa.musicplaylistmanager.player.strategy;
    opens org.unisa.musicplaylistmanager.player.strategy to javafx.fxml;
    exports org.unisa.musicplaylistmanager.track.model;
    opens org.unisa.musicplaylistmanager.track.model to javafx.fxml;
    exports org.unisa.musicplaylistmanager.track.controller;
    opens org.unisa.musicplaylistmanager.track.controller to javafx.fxml;
    exports org.unisa.musicplaylistmanager.core.statistics;
    opens org.unisa.musicplaylistmanager.core.statistics to javafx.fxml;
    exports org.unisa.musicplaylistmanager.collections;
    opens org.unisa.musicplaylistmanager.collections to javafx.fxml;
    exports org.unisa.musicplaylistmanager.collections.tracklist.model;
    opens org.unisa.musicplaylistmanager.collections.tracklist.model to javafx.fxml;
    exports org.unisa.musicplaylistmanager.collections.tracklist.controller;
    opens org.unisa.musicplaylistmanager.collections.tracklist.controller to javafx.fxml;
    exports org.unisa.musicplaylistmanager.collections.playlist.model;
    opens org.unisa.musicplaylistmanager.collections.playlist.model to javafx.fxml;
    exports org.unisa.musicplaylistmanager.collections.playlist.controller;
    opens org.unisa.musicplaylistmanager.collections.playlist.controller to javafx.fxml;
    exports org.unisa.musicplaylistmanager.collections.playlist.creation;
    opens org.unisa.musicplaylistmanager.collections.playlist.creation to javafx.fxml;
    exports org.unisa.musicplaylistmanager.tag.model;
    opens org.unisa.musicplaylistmanager.tag.model to javafx.fxml;
    exports org.unisa.musicplaylistmanager.tag.controller;
    opens org.unisa.musicplaylistmanager.tag.controller to javafx.fxml;
    exports org.unisa.musicplaylistmanager.tag.service;
    opens org.unisa.musicplaylistmanager.tag.service to javafx.fxml;
}